### ISSUE TITLE
Questions about the division of training sets

### ISSUE THREAD

**Issue by Cai-Yao** [YingtongDou/CARE-GNN#3]
What is the purpose of having equal proportions of positive and negative samples in the training set in the code? I don't know what your test ACC values are, I have a feeling there might be a problem somewhere, the ACC values are not up to 70% yet!

**Comment by YingtongDou** [comment]
Since the two datasets are extremely imbalanced, the algorithm will be biased to predict nodes towards the dominant (negative) class during training. That's the reason why we need to balance training sample classes.

For the Yelp dataset, the test ACC is around 70% when the thresholds converge. What's your concern about the ACC metric?

**Comment by Cai-Yao** [comment]
Thanks for the reply, I initially thought it was an error in implementing your code and I should have paid more attention to the AUC value.

Thanks again for your answer on the training set partitioning

**Comment by YingtongDou** [comment]
You are welcome!
